"""Initial

Revision ID: 8f66d4e73d79
Revises: d16650171574
Create Date: 2023-06-22 21:39:52.198710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f66d4e73d79'
down_revision = 'd16650171574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
